service: newtone-backend

frameworkVersion: '>=4.0.0'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:eu-central-1:*:table/*

plugins:
  - serverless-offline

functions:
  mainApi:
    handler: server-main.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

  stripeWebhook:
    handler: server-stripe.handler
    events:
      - http:
          path: /webhook
          method: POST
          cors: true
          payload: '2.0'   # ⚠ Используется payload v2 для raw body